<a href="https://colab.research.google.com/github/Jeremay01/Linear-Algebra-2nd-Sem/blob/main/Assignment_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Transposition

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
J = np.array([
    [24, 56, 89, 36],
    [42, 65, 98, 63],
    [132, 86, 98, 34]
])
J.shape

(3, 4)

In [ ]:
np.transpose(J).shape

(4, 3)

In [ ]:
J.T.shape

(4, 3)

In [ ]:
JT = J.T
JT

array([[ 24,  42, 132],
       [ 56,  65,  86],
       [ 89,  98,  98],
       [ 36,  63,  34]])

## Dot Product / Inner Products

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
A = np.array([
    [2, 5, 7],
    [3, 5, 12],
    [4, 9, 3]
])
B = np.array([
    [23, 5, 6],
    [6, 4, 2],
    [7, 8, 2]
])
C = np.array([
    [2, 2, 5],
    [4, 6, 1],
    [17, 6, 2]
])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
A.dot(np.eye(3))

array([[ 2.,  5.,  7.],
       [ 3.,  5., 12.],
       [ 4.,  9.,  3.]])

In [ ]:
np.array_equal(A@B, B@A)

False

In [ ]:
J = A + (B + C)
J

array([[27, 12, 18],
       [13, 15, 15],
       [28, 23,  7]])

In [ ]:
J = A @ (B @ C)
J

array([[1206,  982,  783],
       [1774, 1464, 1150],
       [1470, 1102, 1011]])

In [ ]:
J = (B + C) @ A
J

array([[115, 259, 292],
       [ 62, 127, 199],
       [106, 226, 348]])

In [ ]:
H = A @ B @ C
H

array([[1206,  982,  783],
       [1774, 1464, 1150],
       [1470, 1102, 1011]])

In [ ]:
np.array_equal(J, H)

False

In [ ]:
np.array_equiv(J, H)

False

In [ ]:
A @ J

array([[1282, 2735, 4015],
       [1927, 4124, 6047],
       [1336, 2857, 4003]])

In [ ]:
s_mat = np.zeros(A.shape)
s_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a_dot_s = A.dot(np.zeros(A.shape))

In [ ]:
np.array_equal(a_dot_s, s_mat)

True

In [ ]:
null_mat = np.empty(A.shape,dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(a_dot_s,null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

### TASK 1

### Dot Product has special properties

Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions:
 1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$ 

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
I = np.array([
    [2, 5, 7, 7],
    [13, 5, 12, 5],
    [3, 5, 21, 15],
    [4, 7, 93, 7]
])
L = np.array([
    [23, 5, 6, 3],
    [6, 4, 2, 8],
    [6, 8, 1, 9],
    [17, 7, 12,  8]
])
Y = np.array([
    [12, 2, 5, 6],
    [4, 66, 71, 3],
    [4, 6, 82, 3],
    [17, 67, 22, 19]
])


In [ ]:
A = I.dot(L)
B = L.dot(Y)
C = Y.dot(I)
D = I.dot(A)
F = C.dot(Y)
G = I + L
H = Y + L
I = F + A

In [ ]:
print('Property 1')
{np.array_equiv(I, L)}
print('AB=BA')
print('Matrix AB:')
print(np.matmul(A,B))
print('Matrix BA:')
print(np.matmul(B,A))
print('Approved!')

Property 1
AB=BA
Matrix AB:
[[ 217380  568518  718570  159603]
 [ 366610  910350 1176786  263341]
 [ 458233 1206385 1519570  337812]
 [ 951884 2498106 3246554  707335]]
Matrix BA:
[[1064193  690865  424435  787498]
 [ 936434  583982  352112  657426]
 [1231485  750637  464705  843086]
 [1723517 1092711  689431 1241755]]
Approved!


In [ ]:
print('Property 2')
{np.array_equiv(I.dot(L), L.dot(Y))}
print('A(BC) = (AB)C')
print('Matrix A(BC):')
print(np.matmul(I, L))
print('Matrix A(BC):')
print(np.matmul(L, Y))
print('Approved!')

Property 2
A(BC) = (AB)C
Matrix A(BC):
[[ 959998  832308  274713 1013313]
 [4716105 3626929 1464737 4520023]
 [3672396 2860862 1146884 3590907]
 [4380269 3631361 1283925 4418361]]
Matrix A(BC):
[[ 371  613 1028  228]
 [ 232  824  654  206]
 [ 261 1149  878  234]
 [ 416 1104 1742  311]]
Approved!


In [ ]:
print('Property 3')
{np.array_equiv(C.dot(Y), D)}
print('Matrix A(B+C)')
print(np.matmul(C, Y))
print('Matrix (AB) + (AC):')
print(np.add(Y, D))
print('Approved!')

Property 3
Matrix A(B+C)
[[  8287  27983  78036   7267]
 [ 50904 162386 301149  43930]
 [ 36709 132743 236951  34681]
 [ 43413 126203 330946  35150]]
Matrix (AB) + (AC):
[[  8299  27985  78041   7273]
 [ 50908 162452 301220  43933]
 [ 36713 132749 237033  34684]
 [ 43430 126270 330968  35169]]
Approved!


In [ ]:
print('Property 4')
{np.array_equiv(I.dot(A), I)}
print('(B+C)A = (BA) + (CA)')
print('Matrix (B+C)A:')
print(np.matmul(I, A))
print('Matrix (BA) + (CA):')
print(np.add(I, I))
print('Approved!')

Property 4
(B+C)A = (BA) + (CA)
Matrix (B+C)A:
[[ 59224408  37544432  24956093  42908740]
 [271643649 171998891 110316906 195693503]
 [215739608 136278770  87338122 154921681]
 [260467773 165778683 108924086 189394257]]
Matrix (BA) + (CA):
[[ 17048  56236 156298  14864]
 [102780 325204 602618  88314]
 [ 74378 266102 474360  70078]
 [ 88448 254088 662322  72222]]
Approved!


In [ ]:
print('Property 5')
{np.array_equiv(Y.dot(1), D)}
print('A(1)=A')
print('Matrix A(1):')
print(np.multiply(Y, 1))
print('Matrix A:')
print(D)
print('Approved!')

Property 5
A(1)=A
Matrix A(1):
[[12  2  5  6]
 [ 4 66 71  3]
 [ 4  6 82  3]
 [17 67 22 19]]
Matrix A:
[[  8287  27983  78036   7267]
 [ 50904 162386 301149  43930]
 [ 36709 132743 236951  34681]
 [ 43413 126203 330946  35150]]
Approved!


In [ ]:
print('Property 6')
{np.array_equiv(L.dot(0), 0)}
print('A(0)=0')
print('Matrix A(0):')
print(np.multiply(A, 0))
print('Approved!')

Property 6
A(0)=0
Matrix A(0):
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Approved!
